### ISSUE TITLE
wrong mkdir access rights

### ISSUE THREAD

**Issue by tobiasbeckert** [WURFL/wurfl-cloud-client-php#6]
When using the file cache on multiple user instances mkdir() uses the umask of the current user and may not be able to chmod the created directory to 0777.
So we need to reset the umask before using mkdir.

**Comment by kamermans** [comment]
It would be nice to find a way to do this without `umask()`, since it changes the umask for the entire process (it's not thread safe).  Any files/dirs created during that short `umask(0)` timeframe in another thread will end up with a wide-open umask.

Let me run some quick tests and see how this is handled in PHP-FPM and Apache a second.

CC @lucor

**Comment by kamermans** [comment]
In testing `php-fpm`, I see that the `umask` is reset each time the script exits, and does not affect neighboring worker processes, since they are not threads, and since each worker only runs one PHP script at a time, it seems there is no thread-safety problem there.  There are very few people using Apache in a multithreaded way, so I'm not very concerned about that.

 In the wild I see other well-respected projects like `thephpleague/flysystem` are also using `umask`: https://github.com/thephpleague/flysystem/blob/a7374be92c961f8fa9af7eccdaf35c2e71059330/src/Adapter/Local.php#L101-L103

For this reason, I would be OK with merging this PR (#7).  I'll wait for comments until tomorrow and merge if everything is fine.

Thanks for the bug report @tobiasbeckert!

**Comment by kamermans** [comment]
Merged fix in PR #7
